### ISSUE TITLE
Readme file 

### ISSUE THREAD

**Issue by alberto2perez** [johnpaulmedina/laravel-usps#1]
Hi there, don't know if this is the appropriate place to contact you, anyway here it goes ... I am trying to use this package in laravel 5.2, I added 

```
    Usps\UspsServiceProvider::class
```

on config/app.php 

But still I am getting Fatal error: Class 'USPS\Rate' not found

Could you please provide some basic info, usually a readme file, of how to use the package.

Thank you for sharing,

Kind Regards

**Comment by johnpaulmedina** [comment]
Hi,

Sorry for the delay. I built this package for internal use but I will be more than happy to share and update documentation. I am on my mobile now and will be in front of a computer shortly. I'll make sure you have the updated repo and add a readme with instructions.

**Comment by johnpaulmedina** [comment]
@alberto2perez Please see updated commit with README. Feel free to contribute to the methods available. If you need further instructions don't hesitate to reach back out to me.
