### ISSUE TITLE
Composer Autoload issues

### ISSUE THREAD

**Issue by audetcameron** [johnpaulmedina/laravel-usps#10]
Looks like there are some issues with composer autoload that will become a problem in composer 2.
![image](https://user-images.githubusercontent.com/6738453/77758914-33d80380-700a-11ea-8f23-918d901a820b.png)

**Comment by audetcameron** [comment]
wonder if class namespaces have to  be 
```
namespace Johnpaulmedina\Usps\Usps;
```
due to this 
![image](https://user-images.githubusercontent.com/6738453/77759991-0c823600-700c-11ea-9791-06d4587ca91c.png)

Thoughts?

**Comment by johnpaulmedina** [comment]
Thank you for pointing this out. Looking into now.
