### ISSUE TITLE
Laravel 7.10.3

### ISSUE THREAD

**Issue by cvhainb** [johnpaulmedina/laravel-usps#12]
Hello John,

I can't install on Laravel 7.10.3. Please advise. 

> Problem 1
>     - Installation request for johnpaulmedina/laravel-usps ^6.0 -> satisfiable by johnpaulmedina/laravel-usps[6.0].
>     - Conclusion: remove laravel/framework v7.10.3
>     - Conclusion: don't install laravel/framework v7.10.3
>     - johnpaulmedina/laravel-usps 6.0 requires illuminate/support ^6.0 -> satisfiable by illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
>     - don't install illuminate/support 6.x-dev|don't install laravel/framework v7.10.3

**Comment by johnpaulmedina** [comment]
Working on 7.0 support should be available later today
