### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by happyclicker** [johnpaulmedina/laravel-usps#15]
When using composer to install on a Laravel 8 instance, I get the following error:

Problem 1
    - johnpaulmedina/laravel-usps[7.0.1, ..., 7.0.x-dev] require illuminate/support ^7.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires johnpaulmedina/laravel-usps ^7.0 -> satisfiable by johnpaulmedina/laravel-usps[7.0.1, 7.0.2, 7.0.x-dev].

**Comment by daveore090** [comment]
i guess you can fork it and work your way around it
i hope to do so soon as i need this package urgently
