### ISSUE TITLE
New XML2Array error parsing XML string

### ISSUE THREAD

**Issue by ChrisHardie** [johnpaulmedina/laravel-usps#28]
This may be a local/environment issue but today my application started throwing exceptions when running `Johnpaulmedina\Usps\Facades\Usps::validate()`:

```
WARNING  DOMDocument::loadXML(): Start tag expected, '<' not found in Entity, line: 1 in vendor/johnpaulmedina/laravel-usps/src/XML2Array.php on line 68. 
Exception  [XML2Array] Error parsing the XML string
```

Happens with every address verification attempt. Didn't make any changes to the way the package was installed or used, nor to PHP or Laravel, so I'm wondering if USPS started returning something different. I'm looking for a way to debug this further by inspecting the API response.

Editing to add: Found that if I dump the response around https://github.com/johnpaulmedina/laravel-usps/blob/master/src/USPSBase.php#L197 it's a stream of special characters, so maybe some kind of encoding or gzip/compression issue. But without anything changing in my environment between it working one minute and erroring the next, I'm still looking at USPS as the source of the bug/change.

**Comment by johnpaulmedina** [comment]
This could be a USPS API implementation. I see someone created a PR I am going to review and test now.

**Comment by johnpaulmedina** [comment]
I merged some code, can you try now?

**Comment by ChrisHardie** [comment]
Short version: I don't think this was an issue with this package.

Longer version: USPS seems to have blocked access to their address verification API from Digital Ocean IP addresses, and further, their error message indicating that block was being sent in gzipped format even though accepting gzipped/compressed data was not indicated in the request, so it looked like gibberish to the curl client instead of a valid XML response. Quite a mess, but sorry to bother you with it.
