### ISSUE TITLE
Laravel 6 upgrade

### ISSUE THREAD

**Issue by ctwillie** [johnpaulmedina/laravel-usps#6]
Great package. I really appreciate it. Was wondering when or if you planned on support for Laravel 6.

**Comment by johnpaulmedina** [comment]
I will try to get around to it this weekend. Thanks for feedback.

**Comment by ctwillie** [comment]
Thanks a lot.

**Comment by johnpaulmedina** [comment]
Don't want you to think I forgot. Unfortunately I caught the flu and pneumonia but all better now. Kids bring home these things from school. Ill get on this asap.

**Comment by johnpaulmedina** [comment]
Merged by PR

**Comment by ctwillie** [comment]
Glad you are feeling better. Funny thing is I am in the middle of writing my own wrapper for their API. I'm growing as a developer and think its time I write some things of my own. Your package was the last dependency preventing us from upgrading to Laravel 6 and thought it was a perfect opportunity. I'm going to finish it primarily for personal development. But we can upgrade now thanks to you. Much appreciated. I'll write when I finish it and would appreciate your opinion on my code if you are up to it. Have a good one.
