### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by code2prog** [johnpaulmedina/laravel-usps#7]
There is a specific reason why communication with api is done without SSL?
I try to implement to your package returning label feature but api MerchandiseReturnV4 requires secure connection.
`API Disabled: MerchandiseReturnV4.  API Disabled: This API requires an SSL connection.`

**Comment by johnpaulmedina** [comment]
This is a wrapper for an existing PHP Wrapper to the USPS Library and should not be done without SSL. Can you send some screen shots of your implementation?

**Comment by code2prog** [comment]
My new class extends USPSBase.USPSBase has hardcoded api url with non https. I think this is main issue.
```
const LIVE_API_URL = 'http://production.shippingapis.com/ShippingAPI.dll';
    const TEST_API_URL = 'http://production.shippingapis.com/ShippingAPITest.dll';
```

**Comment by bredmor** [comment]
The lib this is based on updated to using SSL in may (See: https://github.com/VinceG/USPS-php-api/commit/5787470b5bc3d37792c85c5b0f4a22fdf6d579cf). You just need to merge from upstream @johnpaulmedina

**Comment by code2prog** [comment]
Thanks
